#!/bin/bash

# 🎉 Warehouse Management System Backend - Installation Instructions
# ====================================================================

echo "=========================================="
echo "  Warehouse Management System Backend"
echo "  Complete Installation Guide"
echo "=========================================="
echo ""

echo "📦 Step 1: Install Dependencies"
echo "--------------------------------"
echo "Run: npm install"
echo ""
echo "This will install:"
echo "  • Express.js framework"
echo "  • TypeScript and type definitions"
echo "  • Prisma ORM"
echo "  • JWT authentication"
echo "  • All other dependencies"
echo ""

echo "⚙️  Step 2: Configure Environment"
echo "--------------------------------"
echo "Run: cp .env.example .env"
echo ""
echo "Then edit .env and set:"
echo "  • DATABASE_URL (PostgreSQL connection)"
echo "  • JWT_SECRET (random secure string)"
echo "  • ALLOWED_ORIGINS (frontend URLs)"
echo ""

echo "🗄️  Step 3: Setup Database"
echo "--------------------------------"
echo "Create PostgreSQL database:"
echo "  createdb warehouse_db"
echo ""
echo "Run migrations:"
echo "  npm run prisma:generate"
echo "  npm run prisma:migrate"
echo ""
echo "Seed sample data (optional):"
echo "  npm run seed"
echo ""

echo "🚀 Step 4: Start Development Server"
echo "--------------------------------"
echo "Run: npm run dev"
echo ""
echo "Server will start at: http://localhost:3000"
echo "Health check: http://localhost:3000/health"
echo ""

echo "📖 DOCUMENTATION"
echo "================"
echo "• README.md - Complete API documentation"
echo "• QUICKSTART.md - Quick setup guide"
echo "• API_TESTS.md - API testing examples"
echo "• DEPLOYMENT.md - Production deployment"
echo "• INDEX.md - Documentation index"
echo ""

echo "🔑 DEFAULT USERS (after seeding)"
echo "================================"
echo "Admin:   admin@warehouse.com / admin123"
echo "Manager: manager@warehouse.com / manager123"
echo "Agent:   agent@warehouse.com / agent123"
echo ""

echo "✨ QUICK START"
echo "=============="
echo "For automated setup, run:"
echo "  chmod +x setup.sh"
echo "  ./setup.sh"
echo ""

echo "📚 NEED HELP?"
echo "============"
echo "Check INDEX.md for complete documentation guide"
echo ""

echo "Happy coding! 🎉"

